config/routes.rb
Rails.application.routes.draw do
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  get("/", to: "ideas#index", as: :root)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # if user.is_admin?
    #   can :manage, :all
    # end

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Idea, user_id: user.id
    can :crud, Review, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 50 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :set_idea

  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  helper_method(:current_user)

  def user_signed_in?
    current_user.present?
  end

  helper_method(:user_signed_in?)

  def authenticate_user!
    unless user_signed_in?
      session[:return_to] ||= request.url
      flash[:warning] = "You Must Sign In or Sign Up First"
      redirect_to new_session_path
    end
  end

  def set_idea
    @idea = Idea.new
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:destroy, :edit, :update]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to idea_url(@idea)
    else
      render :new
    end
  end

  def show
    @new_review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
  end

  def index
    @ideas = Idea.all.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @idea.update idea_params
      flash[:success] = "Idea Updated Successfully!"
      redirect_to (idea_path(@idea))
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    flash[:success] = "Your Idea Has Been Deleted!"
    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: "Access Denied: That Post Isn't Yours!" unless can? :crud, @idea
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @idea = Idea.find params[:idea_id]
    @new_review = Review.new review_params
    @new_review.idea = @idea
    @new_review.user = current_user
    if @new_review.save
      redirect_to idea_url(@idea)
    else
      @reviews = @idea.reviews.order(created_at: :desc)
      render "ideas/show"
    end
  end

  def destroy
    @review = Review.find params[:id]
    if can? :destroy, @review
      @review.destroy
      flash[:success] = "Review Deleted!"
      redirect_to idea_url(@review.idea)
    else
      flash[:alert] = "Access Denied: That review Isn't Yours!"
      redirect_to root_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to root_path
    else
      flash[:warning] = "Wrong Email or Password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You Are Now Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :find_user, only: [:edit, :update]
  before_action :authorize_user!, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Signed Up Successfully!"
      redirect_to root_path
    else
      flash[:warning] = "You Entered Something Incorrectly"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[:success] = "Personal Info Updated!"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end

  def find_user
    @user = User.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: "Access Denied: You Can Only Edit Your Own Info!" unless can? :update, @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "warning" then "alert alert-warning"
    when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: @idea, local: true) do |f| %>

        <div class="form-group">
          <% if @idea.errors.present? %>
            <p>
              <%= @idea.errors.full_messages.join(", ") %>
            </p>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :title %> <br>
          <%= f.text_field :title, size: "85", class: "form-control" %>
        </div>

        <div class="form-group"> 
          <%= f.label :description %> <br>
          <%= f.text_area :description, size: "85", cols: 60, rows: 5, class: "form-control" %>
        </div>

        <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-outline-info" %>
      </div>
  
    <% end %>

app/views/ideas/edit.html.erb
<div class="container">
  <div class="form-align">
    <div class="form-group">
      <h4>Edit Idea</h4>
    </div>
    
    <%= render "form" %>

  </div>
</div>

app/views/ideas/index.html.erb
<div class="jumbo-box">
<% @ideas.each do |idea| %>
  <div class="jumbotron">
    <div class="container">
      <h3><i class="fa fa-plus"></i>&nbsp&nbsp<%= link_to idea.title, idea_path(idea.id), class: "text-info" %></h3>
      <p class="lead" style="display: none"><%= idea.description %></p>
      <hr class="my-4">
      <small class="text-muted">
        Posted by <span class="text-info"><%= idea.user&.name || '--deleted--' %></span>
        <%= time_ago_in_words(idea.created_at) %> ago
      </small>
    </div>
  </div>
<% end %>

app/views/ideas/new.html.erb
<div class="container">
  <div class="form-align">
    <div class="form-group">
      <h4>New Idea</h4>
    </div>
    
    <%= render "form" %>

  </div>
</div>

app/views/ideas/show.html.erb
<div class="jumbo-box">
  <div class="jumbotron">
    <div class="container">
      <h3 class="text-info"><%= @idea.title %></h3>
      <p class="lead"><%= @idea.description %></p>
      <hr class="my-4">
      <small class="text-muted">
        Posted by <span class="text-info"><%= @idea.user&.name || '--deleted--' %></span>
        <%= time_ago_in_words(@idea.created_at) %> ago
      </small>
      <% if can? :crud, @idea %>
        <div>
          <%= link_to "Edit", edit_idea_path(@idea.id), class: "btn btn-outline-info" %>
          <%= link_to "Delete", idea_path(@idea.id), method: :delete, class: "btn btn-outline-info", data: { confirm: "Are you sure you want to delete your idea?" } %>
        </div>
      <% end %>
      <section>
      <div class="review-box">
        <h5 class="text-info">Reviews</h5>

        <%= form_with(model: [@idea, @new_review], local: true) do |f| %>
            <div class="form-group">
              <% if @new_review.errors.present? %>
                <p>
                  <%= @new_review.errors.full_messages.join(', ') %>
                </p>
              <% end %>
            </div>

            <div class="form_group">
              <%= f.text_area(
                :body,
                cols: 50,
                rows: 4,
                placeholder: "What's on your mind?",
                class: "form-control"
              ) %> 
            </div>
            <div class="review-button">
              <%= f.submit "Submit", class: "btn btn-outline-info" %>
            </div>
          <% end %>
          <div class="review-box">
            <ul class="review-list">
              <% @reviews.each do |review| %>
                <li>
                  <p>
                    <%= review.body %> <br>
                    <small class="text-muted">
                      Reviewed by <span class="text-info"><%= review.user&.name || "--deleted--" %></span>  
                      <%= time_ago_in_words(review.created_at) %> ago
                    </small>
                    <% if can?(:destroy, review)%>
                      •
                      <small>
                        <%=
                          link_to(
                            "Delete",
                            idea_review_path(@idea, review),
                            method: :delete,
                            data: {
                              confirm: "Are you sure?"
                            },
                            class: "text-info"
                          )
                        %>
                      </small>
                    <% end %>
                  </p>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cool Ideas!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  
  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark bg-info">
        <span class="text-white"><%= link_to image_tag("idea.png"), root_path, class: "navbar-brand nav-logo" %>&nbsp The Idea Factory</span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="nav-container">
              <%= link_to "Ideas", root_path, class: "nav-item nav-link form-inline btn btn-secondary nav-btn-spacer" %>
              <% if user_signed_in? %>
              <button type="button" class="btn btn-secondary nav-item nav-link form-inline nav-btn-spacer" data-toggle="modal" data-target="#exampleModalCenter">
                New Idea!
              </button>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Sign Out", session_path, method: :delete, data: { confirm: "Are You Sure You Want to Sign Out?" }, class: "nav-item nav-link form-inline btn btn-secondary nav-btn-spacer" %>
                <span class="navspan text-white"> Hello,&nbsp <%= current_user.name %>!</span>
              <% else %>
                <%= link_to "Sign In", new_session_path, class: "nav-item nav-link form-inline btn btn-secondary nav-btn-spacer" %> 
                <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link form-inline btn btn-secondary nav-btn-spacer" %>
              <% end %>
          </div>
        </div>
      </nav>
      <div class="alert-box">
        <% flash.each do |type, message| %>
          <div class="<%= flash_class(type) %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
      </div>
    </header>
  <% if user_signed_in? %>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">New Idea!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
  <% end %>
    <main>
      <%= yield %>
    </main> 
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
  <div class="form-align">
    <div class="form-group">
      <h4>Sign Up</h4>
    </div>
    
    <%= form_with model: @user, local: true do |f| %>

      <div class="form-group">
        <% if @user.errors.any? %>
          <p>
            <%= @user.errors.full_messages.join(", ") %>
          </p>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :name %> <br>
        <%= f.text_field :name, size: "85", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %> <br>
        <%= f.email_field :email, size: "85", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %> <br>
        <%= f.password_field :password, size: "85", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %> <br>
        <%= f.password_field :password_confirmation, size: "85", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Sign Up", class: "btn btn-outline-info" %>
      </div>

    <% end %>
  </div>
</div>